const AUTOMATIC_VERSION_QUIET_PERIOD_MS = 10 * 60 * 1000;
const AUTOMATIC_VERSION_MAX_PERIOD_MS = 60 * 60 * 1000;
const AUTOMATIC_VERSION_QUEUE_INTERVAL_MS = 5 * 60 * 1000;

export {
  AUTOMATIC_VERSION_MAX_PERIOD_MS,
  AUTOMATIC_VERSION_QUEUE_INTERVAL_MS,
  AUTOMATIC_VERSION_QUIET_PERIOD_MS
};
